<?php
return [
  [
    'title' => '工作区',
    'icon' => '',
    'module' => 'system',
    'url' => 'system/work',
    'param' => '',
    'target' => '_self',
    'debug' => 0,
    'system' => 1,
    'nav' => 1,
    'sort' => 0,
    'childs' => [
      [
        'title' => '居民信息',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'resident/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 1,
        'childs' => [
          [
            'title' => '信息卡',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'system',
            'url' => 'resident/info/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加信息卡',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'resident/info/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
          [
            'title' => '人员列表',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'system',
            'url' => 'resident/member/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
          ],
        ],
      ],
      [
        'title' => '来访登记',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'visitor',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 2,
        'childs' => [
          [
            'title' => '来访登记管理',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'system',
            'url' => 'visitor/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加登记',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'visitor/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '证明信',
        'icon' => 'aicon ai-caidan',
        'module' => 'certificate',
        'url' => 'certificate/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 3,
        'childs' => [
          [
            'title' => '证明信管理',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'certificate',
            'url' => 'certificate/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '添加证明信',
                'icon' => 'aicon ai-shezhi',
                'module' => 'certificate',
                'url' => 'certificate/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改证明信',
                'icon' => 'aicon ai-shezhi',
                'module' => 'certificate',
                'url' => 'certificate/index/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '证明信删除',
                'icon' => 'aicon ai-shezhi',
                'module' => 'certificate',
                'url' => 'certificate/index/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '就业证明',
        'icon' => 'aicon ai-caidan',
        'module' => 'work_proof',
        'url' => 'work_proof/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 4,
        'childs' => [
          [
            'title' => '就业证明管理',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'work_proof',
            'url' => 'work_proof/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 1,
            'childs' => [
              [
                'title' => '添加就业证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'work_proof',
                'url' => 'work_proof/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 1,
                'sort' => 0,
              ],
              [
                'title' => '修改就业证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'work_proof/index/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除就业证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'work_proof',
                'url' => 'work_proof/index/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '死亡证明',
        'icon' => 'aicon ai-caidan',
        'module' => 'system',
        'url' => 'death_proof/index',
        'param' => '',
        'target' => '_self',
        'debug' => 0,
        'system' => 0,
        'nav' => 1,
        'sort' => 5,
        'childs' => [
          [
            'title' => '死亡证明管理',
            'icon' => 'typcn typcn-clipboard',
            'module' => 'system',
            'url' => 'death_proof/index/index',
            'param' => '',
            'target' => '_self',
            'debug' => 0,
            'system' => 0,
            'nav' => 1,
            'sort' => 0,
            'childs' => [
              [
                'title' => '添加死亡证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'death_proof/index/add',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '修改死亡证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'death_proof/index/edit',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
              [
                'title' => '删除死亡证明',
                'icon' => 'aicon ai-shezhi',
                'module' => 'system',
                'url' => 'death_proof/index/del',
                'param' => '',
                'target' => '_self',
                'debug' => 0,
                'system' => 0,
                'nav' => 0,
                'sort' => 0,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
